### ISSUE TITLE
Thêm thông tin môn học

### ISSUE THREAD

**Issue by TinDang97** [TDTU-IT-DP/51900192-51900210#1]
https://github.com/TDTU-IT-DP/51900192-51900210/blob/7e883e739c4cb60b849521e9aff5fef92c0fa71d/README.md?plain=1#L1-L8

Em vui lòng thêm tên môn học, niên khóa nha...
Người hướng dẫn nữa. Tại anh phải nộp về khoa

**Comment by qnpDev** [comment]
em đã update thêm vào readme rồi ạ. em cảm ơn anh!
